name: FTSSurvival
version: "1.3.1"
main: de.ftscraft.survivalminus.main.Survival
author: halberfan
api-version: "1.15"

depend: [ProtocolLib]

commands:
    gesundheit:
    chooseability:
    givewater:
    beruf: